// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeImage(arg1) {
  return window['go']['main']['App']['AnalyzeImage'](arg1);
}

export function BrowseDirectory(arg1) {
  return window['go']['main']['App']['BrowseDirectory'](arg1);
}

export function CancelQueue() {
  return window['go']['main']['App']['CancelQueue']();
}

export function CancelQueueJob(arg1) {
  return window['go']['main']['App']['CancelQueueJob'](arg1);
}

export function CheckRembg() {
  return window['go']['main']['App']['CheckRembg']();
}

export function CheckServices() {
  return window['go']['main']['App']['CheckServices']();
}

export function ClearCompletedQueueJobs() {
  return window['go']['main']['App']['ClearCompletedQueueJobs']();
}

export function ClearLastImage() {
  return window['go']['main']['App']['ClearLastImage']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function ConfirmClose(arg1) {
  return window['go']['main']['App']['ConfirmClose'](arg1);
}

export function CreateCompoundPreset(arg1) {
  return window['go']['main']['App']['CreateCompoundPreset'](arg1);
}

export function CreateDescription(arg1) {
  return window['go']['main']['App']['CreateDescription'](arg1);
}

export function CreateDescriptionFull(arg1) {
  return window['go']['main']['App']['CreateDescriptionFull'](arg1);
}

export function CreateHiresProfile(arg1) {
  return window['go']['main']['App']['CreateHiresProfile'](arg1);
}

export function CreatePreset(arg1) {
  return window['go']['main']['App']['CreatePreset'](arg1);
}

export function CreatePresetType(arg1) {
  return window['go']['main']['App']['CreatePresetType'](arg1);
}

export function CreatePrompt(arg1) {
  return window['go']['main']['App']['CreatePrompt'](arg1);
}

export function CreateResolution(arg1) {
  return window['go']['main']['App']['CreateResolution'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DecomposeScene(arg1) {
  return window['go']['main']['App']['DecomposeScene'](arg1);
}

export function DeleteCompoundPreset(arg1) {
  return window['go']['main']['App']['DeleteCompoundPreset'](arg1);
}

export function DeleteDescription(arg1) {
  return window['go']['main']['App']['DeleteDescription'](arg1);
}

export function DeleteExportPreset(arg1) {
  return window['go']['main']['App']['DeleteExportPreset'](arg1);
}

export function DeleteHiresProfile(arg1) {
  return window['go']['main']['App']['DeleteHiresProfile'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function DeletePresetType(arg1) {
  return window['go']['main']['App']['DeletePresetType'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteResolution(arg1) {
  return window['go']['main']['App']['DeleteResolution'](arg1);
}

export function DeleteSavedScene(arg1) {
  return window['go']['main']['App']['DeleteSavedScene'](arg1);
}

export function DeleteServerLLMModel(arg1) {
  return window['go']['main']['App']['DeleteServerLLMModel'](arg1);
}

export function DeleteServerModel(arg1, arg2) {
  return window['go']['main']['App']['DeleteServerModel'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSessionItem(arg1) {
  return window['go']['main']['App']['DeleteSessionItem'](arg1);
}

export function DiscoverServers() {
  return window['go']['main']['App']['DiscoverServers']();
}

export function DownloadServerModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadServerModel'](arg1, arg2, arg3);
}

export function EnqueueCompareItem(arg1, arg2) {
  return window['go']['main']['App']['EnqueueCompareItem'](arg1, arg2);
}

export function EnqueueCompound(arg1) {
  return window['go']['main']['App']['EnqueueCompound'](arg1);
}

export function EnqueueFromImage(arg1) {
  return window['go']['main']['App']['EnqueueFromImage'](arg1);
}

export function EnqueueTxt2Img(arg1) {
  return window['go']['main']['App']['EnqueueTxt2Img'](arg1);
}

export function ExportCompoundPresets(arg1) {
  return window['go']['main']['App']['ExportCompoundPresets'](arg1);
}

export function ExportImage(arg1) {
  return window['go']['main']['App']['ExportImage'](arg1);
}

export function ExportPresets(arg1) {
  return window['go']['main']['App']['ExportPresets'](arg1);
}

export function FastSaveImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['FastSaveImage'](arg1, arg2, arg3);
}

export function GenerateCompoundImage(arg1) {
  return window['go']['main']['App']['GenerateCompoundImage'](arg1);
}

export function GenerateFromImage(arg1) {
  return window['go']['main']['App']['GenerateFromImage'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['main']['App']['GenerateImage'](arg1);
}

export function GenerateMultiPass(arg1) {
  return window['go']['main']['App']['GenerateMultiPass'](arg1);
}

export function GenerateSDPrompt(arg1) {
  return window['go']['main']['App']['GenerateSDPrompt'](arg1);
}

export function GetActiveSessionItem() {
  return window['go']['main']['App']['GetActiveSessionItem']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetCompoundPreset(arg1) {
  return window['go']['main']['App']['GetCompoundPreset'](arg1);
}

export function GetDefaultAnalyzePrompts() {
  return window['go']['main']['App']['GetDefaultAnalyzePrompts']();
}

export function GetDefaultPromptInstruction() {
  return window['go']['main']['App']['GetDefaultPromptInstruction']();
}

export function GetFooterHeight() {
  return window['go']['main']['App']['GetFooterHeight']();
}

export function GetHiresProfile(arg1) {
  return window['go']['main']['App']['GetHiresProfile'](arg1);
}

export function GetKidsCategories() {
  return window['go']['main']['App']['GetKidsCategories']();
}

export function GetLLMModels() {
  return window['go']['main']['App']['GetLLMModels']();
}

export function GetLastImage() {
  return window['go']['main']['App']['GetLastImage']();
}

export function GetModelCatalog() {
  return window['go']['main']['App']['GetModelCatalog']();
}

export function GetPreset(arg1) {
  return window['go']['main']['App']['GetPreset'](arg1);
}

export function GetPresetType(arg1) {
  return window['go']['main']['App']['GetPresetType'](arg1);
}

export function GetPresetsInstallStatus() {
  return window['go']['main']['App']['GetPresetsInstallStatus']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetResolution(arg1) {
  return window['go']['main']['App']['GetResolution'](arg1);
}

export function GetSDLoRAs() {
  return window['go']['main']['App']['GetSDLoRAs']();
}

export function GetSDModels() {
  return window['go']['main']['App']['GetSDModels']();
}

export function GetSDSamplers() {
  return window['go']['main']['App']['GetSDSamplers']();
}

export function GetSDSchedulers() {
  return window['go']['main']['App']['GetSDSchedulers']();
}

export function GetSDUpscalers() {
  return window['go']['main']['App']['GetSDUpscalers']();
}

export function GetSDVAEs() {
  return window['go']['main']['App']['GetSDVAEs']();
}

export function GetSavedScene(arg1) {
  return window['go']['main']['App']['GetSavedScene'](arg1);
}

export function GetServerBackends() {
  return window['go']['main']['App']['GetServerBackends']();
}

export function GetServerLLMModels() {
  return window['go']['main']['App']['GetServerLLMModels']();
}

export function GetServerModels(arg1) {
  return window['go']['main']['App']['GetServerModels'](arg1);
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSessionImage(arg1) {
  return window['go']['main']['App']['GetSessionImage'](arg1);
}

export function GetSessionItems() {
  return window['go']['main']['App']['GetSessionItems']();
}

export function GetSessionThumb(arg1) {
  return window['go']['main']['App']['GetSessionThumb'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasSessionItems() {
  return window['go']['main']['App']['HasSessionItems']();
}

export function ImportCompoundPresets(arg1) {
  return window['go']['main']['App']['ImportCompoundPresets'](arg1);
}

export function ImportPresets(arg1) {
  return window['go']['main']['App']['ImportPresets'](arg1);
}

export function InstallPresetDeps(arg1) {
  return window['go']['main']['App']['InstallPresetDeps'](arg1);
}

export function InterruptGeneration() {
  return window['go']['main']['App']['InterruptGeneration']();
}

export function IsKidsModeActive() {
  return window['go']['main']['App']['IsKidsModeActive']();
}

export function IsQueuePaused() {
  return window['go']['main']['App']['IsQueuePaused']();
}

export function ListCompoundPresets() {
  return window['go']['main']['App']['ListCompoundPresets']();
}

export function ListDescriptions() {
  return window['go']['main']['App']['ListDescriptions']();
}

export function ListExportPresets() {
  return window['go']['main']['App']['ListExportPresets']();
}

export function ListHiresProfiles() {
  return window['go']['main']['App']['ListHiresProfiles']();
}

export function ListPresetTypes() {
  return window['go']['main']['App']['ListPresetTypes']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function ListPresetsByType(arg1) {
  return window['go']['main']['App']['ListPresetsByType'](arg1);
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListResolutions() {
  return window['go']['main']['App']['ListResolutions']();
}

export function ListSavedScenes() {
  return window['go']['main']['App']['ListSavedScenes']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function OpenImportCompoundFile() {
  return window['go']['main']['App']['OpenImportCompoundFile']();
}

export function OpenImportFile() {
  return window['go']['main']['App']['OpenImportFile']();
}

export function PauseQueue() {
  return window['go']['main']['App']['PauseQueue']();
}

export function PrepareCompoundPresetsExport(arg1) {
  return window['go']['main']['App']['PrepareCompoundPresetsExport'](arg1);
}

export function PreparePresetsExport(arg1) {
  return window['go']['main']['App']['PreparePresetsExport'](arg1);
}

export function PullServerLLMModel(arg1) {
  return window['go']['main']['App']['PullServerLLMModel'](arg1);
}

export function ReadClipboardImage() {
  return window['go']['main']['App']['ReadClipboardImage']();
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function ReadImageFile() {
  return window['go']['main']['App']['ReadImageFile']();
}

export function ReadThumbnail(arg1) {
  return window['go']['main']['App']['ReadThumbnail'](arg1);
}

export function RecommendPreset(arg1) {
  return window['go']['main']['App']['RecommendPreset'](arg1);
}

export function RemoveQueueJob(arg1) {
  return window['go']['main']['App']['RemoveQueueJob'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RestartServerProcess(arg1) {
  return window['go']['main']['App']['RestartServerProcess'](arg1);
}

export function ResumePausedQueueJobs() {
  return window['go']['main']['App']['ResumePausedQueueJobs']();
}

export function ResumeQueue() {
  return window['go']['main']['App']['ResumeQueue']();
}

export function SaveExportPreset(arg1) {
  return window['go']['main']['App']['SaveExportPreset'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveScene(arg1) {
  return window['go']['main']['App']['SaveScene'](arg1);
}

export function SaveWindowLayout(arg1) {
  return window['go']['main']['App']['SaveWindowLayout'](arg1);
}

export function SelectBrowserFolder() {
  return window['go']['main']['App']['SelectBrowserFolder']();
}

export function SetActiveSessionItem(arg1) {
  return window['go']['main']['App']['SetActiveSessionItem'](arg1);
}

export function SetKidsCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetKidsCategory'](arg1, arg2, arg3);
}

export function SetKidsMode(arg1, arg2) {
  return window['go']['main']['App']['SetKidsMode'](arg1, arg2);
}

export function SetLastImage(arg1) {
  return window['go']['main']['App']['SetLastImage'](arg1);
}

export function StartServerProcess(arg1) {
  return window['go']['main']['App']['StartServerProcess'](arg1);
}

export function StopServerProcess(arg1) {
  return window['go']['main']['App']['StopServerProcess'](arg1);
}

export function SwitchServerBackend(arg1) {
  return window['go']['main']['App']['SwitchServerBackend'](arg1);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}

export function TestCompoundGenerate(arg1) {
  return window['go']['main']['App']['TestCompoundGenerate'](arg1);
}

export function TestGenerate(arg1) {
  return window['go']['main']['App']['TestGenerate'](arg1);
}

export function UpdateCompoundPreset(arg1) {
  return window['go']['main']['App']['UpdateCompoundPreset'](arg1);
}

export function UpdateDescription(arg1) {
  return window['go']['main']['App']['UpdateDescription'](arg1);
}

export function UpdateHiresProfile(arg1) {
  return window['go']['main']['App']['UpdateHiresProfile'](arg1);
}

export function UpdatePreset(arg1) {
  return window['go']['main']['App']['UpdatePreset'](arg1);
}

export function UpdatePresetType(arg1) {
  return window['go']['main']['App']['UpdatePresetType'](arg1);
}

export function UpdateResolution(arg1) {
  return window['go']['main']['App']['UpdateResolution'](arg1);
}

export function UpdateSavedScene(arg1) {
  return window['go']['main']['App']['UpdateSavedScene'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpscaleImage(arg1) {
  return window['go']['main']['App']['UpscaleImage'](arg1);
}

export function UpscalePreview(arg1) {
  return window['go']['main']['App']['UpscalePreview'](arg1);
}

export function ValidateImportModels(arg1) {
  return window['go']['main']['App']['ValidateImportModels'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
