// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {preset} from '../models';
import {llm} from '../models';
import {sd} from '../models';

export function CheckServices():Promise<main.ServiceStatus>;

export function CreateDescription(arg1:string):Promise<preset.SavedDescription>;

export function CreatePreset(arg1:preset.Preset):Promise<preset.Preset>;

export function CreatePrompt(arg1:string):Promise<preset.SavedPrompt>;

export function DeleteDescription(arg1:number):Promise<void>;

export function DeletePreset(arg1:number):Promise<void>;

export function DeletePrompt(arg1:number):Promise<void>;

export function ExportPresets(arg1:Array<number>):Promise<string>;

export function GenerateImage(arg1:main.GenerateImageParams):Promise<main.GenerateImageResult>;

export function GenerateSDPrompt(arg1:string,arg2:string):Promise<string>;

export function GetLLMModels():Promise<Array<llm.LLMModel>>;

export function GetLastImage():Promise<main.GenerateImageResult>;

export function GetPreset(arg1:number):Promise<preset.Preset>;

export function GetSDModels():Promise<Array<sd.SDModel>>;

export function GetSDSamplers():Promise<Array<sd.Sampler>>;

export function GetSDSchedulers():Promise<Array<sd.Scheduler>>;

export function GetSDUpscalers():Promise<Array<sd.Upscaler>>;

export function GetSDVAEs():Promise<Array<sd.VAE>>;

export function GetSettings():Promise<Record<string, string>>;

export function ImportPresets(arg1:Array<main.PresetData>):Promise<Array<preset.Preset>>;

export function IsKidsModeActive():Promise<boolean>;

export function ListDescriptions():Promise<Array<preset.SavedDescription>>;

export function ListPresets():Promise<Array<preset.Preset>>;

export function ListPresetsByType(arg1:string):Promise<Array<preset.Preset>>;

export function ListPrompts():Promise<Array<preset.SavedPrompt>>;

export function OpenImportFile():Promise<main.ImportPreview>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SetKidsMode(arg1:boolean,arg2:string):Promise<void>;

export function UpdatePreset(arg1:preset.Preset):Promise<preset.Preset>;

export function UpdateSettings(arg1:Record<string, string>):Promise<void>;

export function UpscaleImage(arg1:main.UpscaleImageParams):Promise<main.GenerateImageResult>;

export function UpscalePreview(arg1:main.UpscalePreviewParams):Promise<main.GenerateImageResult>;
