// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {preset} from '../models';
import {main} from '../models';
import {llm} from '../models';
import {sd} from '../models';

export function CreateDescription(arg1:string):Promise<preset.SavedDescription>;

export function CreatePreset(arg1:preset.Preset):Promise<preset.Preset>;

export function DeleteDescription(arg1:number):Promise<void>;

export function DeletePreset(arg1:number):Promise<void>;

export function GenerateImage(arg1:main.GenerateImageParams):Promise<main.GenerateImageResult>;

export function GenerateSDPrompt(arg1:string,arg2:string):Promise<string>;

export function GetLLMModels():Promise<Array<llm.LLMModel>>;

export function GetPreset(arg1:number):Promise<preset.Preset>;

export function GetSDModels():Promise<Array<sd.SDModel>>;

export function GetSDSamplers():Promise<Array<sd.Sampler>>;

export function GetSettings():Promise<Record<string, string>>;

export function ListDescriptions():Promise<Array<preset.SavedDescription>>;

export function ListPresets():Promise<Array<preset.Preset>>;

export function ListPresetsByType(arg1:string):Promise<Array<preset.Preset>>;

export function UpdatePreset(arg1:preset.Preset):Promise<preset.Preset>;

export function UpdateSettings(arg1:Record<string, string>):Promise<void>;
