// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeImage(arg1) {
  return window['go']['main']['App']['AnalyzeImage'](arg1);
}

export function CheckServices() {
  return window['go']['main']['App']['CheckServices']();
}

export function CreateDescription(arg1) {
  return window['go']['main']['App']['CreateDescription'](arg1);
}

export function CreatePreset(arg1) {
  return window['go']['main']['App']['CreatePreset'](arg1);
}

export function CreatePresetType(arg1) {
  return window['go']['main']['App']['CreatePresetType'](arg1);
}

export function CreatePrompt(arg1) {
  return window['go']['main']['App']['CreatePrompt'](arg1);
}

export function DeleteDescription(arg1) {
  return window['go']['main']['App']['DeleteDescription'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function DeletePresetType(arg1) {
  return window['go']['main']['App']['DeletePresetType'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function ExportPresets(arg1) {
  return window['go']['main']['App']['ExportPresets'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['main']['App']['GenerateImage'](arg1);
}

export function GenerateSDPrompt(arg1) {
  return window['go']['main']['App']['GenerateSDPrompt'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetLLMModels() {
  return window['go']['main']['App']['GetLLMModels']();
}

export function GetLastImage() {
  return window['go']['main']['App']['GetLastImage']();
}

export function GetPreset(arg1) {
  return window['go']['main']['App']['GetPreset'](arg1);
}

export function GetPresetType(arg1) {
  return window['go']['main']['App']['GetPresetType'](arg1);
}

export function GetSDLoRAs() {
  return window['go']['main']['App']['GetSDLoRAs']();
}

export function GetSDModels() {
  return window['go']['main']['App']['GetSDModels']();
}

export function GetSDSamplers() {
  return window['go']['main']['App']['GetSDSamplers']();
}

export function GetSDSchedulers() {
  return window['go']['main']['App']['GetSDSchedulers']();
}

export function GetSDUpscalers() {
  return window['go']['main']['App']['GetSDUpscalers']();
}

export function GetSDVAEs() {
  return window['go']['main']['App']['GetSDVAEs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportPresets(arg1) {
  return window['go']['main']['App']['ImportPresets'](arg1);
}

export function IsKidsModeActive() {
  return window['go']['main']['App']['IsKidsModeActive']();
}

export function ListDescriptions() {
  return window['go']['main']['App']['ListDescriptions']();
}

export function ListPresetTypes() {
  return window['go']['main']['App']['ListPresetTypes']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function ListPresetsByType(arg1) {
  return window['go']['main']['App']['ListPresetsByType'](arg1);
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function OpenImportFile() {
  return window['go']['main']['App']['OpenImportFile']();
}

export function ReadImageFile() {
  return window['go']['main']['App']['ReadImageFile']();
}

export function RecommendPreset(arg1) {
  return window['go']['main']['App']['RecommendPreset'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SetKidsMode(arg1, arg2) {
  return window['go']['main']['App']['SetKidsMode'](arg1, arg2);
}

export function UpdatePreset(arg1) {
  return window['go']['main']['App']['UpdatePreset'](arg1);
}

export function UpdatePresetType(arg1) {
  return window['go']['main']['App']['UpdatePresetType'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpscaleImage(arg1) {
  return window['go']['main']['App']['UpscaleImage'](arg1);
}

export function UpscalePreview(arg1) {
  return window['go']['main']['App']['UpscalePreview'](arg1);
}

export function ValidateImportModels(arg1) {
  return window['go']['main']['App']['ValidateImportModels'](arg1);
}
