// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDescription(arg1) {
  return window['go']['main']['App']['CreateDescription'](arg1);
}

export function CreatePreset(arg1) {
  return window['go']['main']['App']['CreatePreset'](arg1);
}

export function DeleteDescription(arg1) {
  return window['go']['main']['App']['DeleteDescription'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['main']['App']['GenerateImage'](arg1);
}

export function GenerateSDPrompt(arg1, arg2) {
  return window['go']['main']['App']['GenerateSDPrompt'](arg1, arg2);
}

export function GetLLMModels() {
  return window['go']['main']['App']['GetLLMModels']();
}

export function GetPreset(arg1) {
  return window['go']['main']['App']['GetPreset'](arg1);
}

export function GetSDModels() {
  return window['go']['main']['App']['GetSDModels']();
}

export function GetSDSamplers() {
  return window['go']['main']['App']['GetSDSamplers']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDescriptions() {
  return window['go']['main']['App']['ListDescriptions']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function ListPresetsByType(arg1) {
  return window['go']['main']['App']['ListPresetsByType'](arg1);
}

export function UpdatePreset(arg1) {
  return window['go']['main']['App']['UpdatePreset'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
