// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {generation} from '../models';
import {filebrowser} from '../models';
import {settings} from '../models';
import {preset} from '../models';
import {compositor} from '../models';
import {importexport} from '../models';
import {kids} from '../models';
import {llm} from '../models';
import {sd} from '../models';

export function AnalyzeImage(arg1:string):Promise<string>;

export function BatchCompoundGenerate(arg1:generation.BatchCompoundGenerateParams):Promise<void>;

export function BatchGenerate(arg1:generation.BatchGenerateParams):Promise<void>;

export function BrowseDirectory(arg1:string):Promise<Array<filebrowser.FileEntry>>;

export function CheckRembg():Promise<void>;

export function CheckServices():Promise<settings.ServiceStatus>;

export function ClearLastImage():Promise<void>;

export function ClearSession():Promise<void>;

export function ConfirmClose(arg1:string):Promise<void>;

export function CreateCompoundPreset(arg1:preset.CompoundPreset):Promise<preset.CompoundPreset>;

export function CreateDescription(arg1:string):Promise<preset.SavedDescription>;

export function CreateDescriptionFull(arg1:preset.SavedDescription):Promise<preset.SavedDescription>;

export function CreateHiresProfile(arg1:preset.HiresProfile):Promise<preset.HiresProfile>;

export function CreatePreset(arg1:preset.Preset):Promise<preset.Preset>;

export function CreatePresetType(arg1:preset.PresetType):Promise<preset.PresetType>;

export function CreatePrompt(arg1:string):Promise<preset.SavedPrompt>;

export function CreateResolution(arg1:preset.Resolution):Promise<preset.Resolution>;

export function CreateSession(arg1:string):Promise<preset.SessionInfo>;

export function DecomposeScene(arg1:generation.DecomposeSceneParams):Promise<compositor.Scene>;

export function DeleteCompoundPreset(arg1:number):Promise<void>;

export function DeleteDescription(arg1:number):Promise<void>;

export function DeleteExportPreset(arg1:number):Promise<void>;

export function DeleteHiresProfile(arg1:number):Promise<void>;

export function DeletePreset(arg1:number):Promise<void>;

export function DeletePresetType(arg1:number):Promise<void>;

export function DeletePrompt(arg1:number):Promise<void>;

export function DeleteResolution(arg1:number):Promise<void>;

export function DeleteSavedScene(arg1:number):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function DeleteSessionItem(arg1:number):Promise<void>;

export function ExportCompoundPresets(arg1:Array<number>):Promise<string>;

export function ExportImage(arg1:importexport.ExportImageParams):Promise<string>;

export function ExportPresets(arg1:Array<number>):Promise<string>;

export function FastSaveImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateCompoundImage(arg1:generation.GenerateCompoundImageParams):Promise<generation.GenerateImageResult>;

export function GenerateFromImage(arg1:generation.GenerateFromImageParams):Promise<generation.GenerateImageResult>;

export function GenerateImage(arg1:generation.GenerateImageParams):Promise<generation.GenerateImageResult>;

export function GenerateMultiPass(arg1:compositor.Scene):Promise<compositor.MultiPassResult>;

export function GenerateSDPrompt(arg1:generation.GenerateSDPromptParams):Promise<generation.GenerateSDPromptResult>;

export function GetActiveSessionItem():Promise<preset.SessionItem>;

export function GetAllTags():Promise<Array<string>>;

export function GetCompoundPreset(arg1:number):Promise<preset.CompoundPreset>;

export function GetDefaultAnalyzePrompts():Promise<generation.AnalyzePrompts>;

export function GetDefaultPromptInstruction():Promise<string>;

export function GetHiresProfile(arg1:number):Promise<preset.HiresProfile>;

export function GetKidsCategories():Promise<Array<kids.CategoryInfo>>;

export function GetLLMModels():Promise<Array<llm.LLMModel>>;

export function GetLastImage():Promise<generation.GenerateImageResult>;

export function GetPreset(arg1:number):Promise<preset.Preset>;

export function GetPresetForBatch(arg1:number,arg2:string):Promise<generation.GenerateSDPromptResult>;

export function GetPresetType(arg1:number):Promise<preset.PresetType>;

export function GetResolution(arg1:number):Promise<preset.Resolution>;

export function GetSDLoRAs():Promise<Array<sd.LoRA>>;

export function GetSDModels():Promise<Array<sd.SDModel>>;

export function GetSDSamplers():Promise<Array<sd.Sampler>>;

export function GetSDSchedulers():Promise<Array<sd.Scheduler>>;

export function GetSDUpscalers():Promise<Array<sd.Upscaler>>;

export function GetSDVAEs():Promise<Array<sd.VAE>>;

export function GetSavedScene(arg1:number):Promise<preset.SavedScene>;

export function GetSessionImage(arg1:number):Promise<string>;

export function GetSessionItems():Promise<Array<preset.SessionItem>>;

export function GetSessionThumb(arg1:number):Promise<string>;

export function GetSettings():Promise<Record<string, string>>;

export function HasSessionItems():Promise<boolean>;

export function ImportCompoundPresets(arg1:Array<importexport.CompoundExportData>):Promise<Array<preset.CompoundPreset>>;

export function ImportPresets(arg1:Array<importexport.PresetData>):Promise<Array<preset.Preset>>;

export function InterruptGeneration():Promise<void>;

export function IsKidsModeActive():Promise<boolean>;

export function ListCompoundPresets():Promise<Array<preset.CompoundPreset>>;

export function ListDescriptions():Promise<Array<preset.SavedDescription>>;

export function ListExportPresets():Promise<Array<preset.ExportPreset>>;

export function ListHiresProfiles():Promise<Array<preset.HiresProfile>>;

export function ListPresetTypes():Promise<Array<preset.PresetType>>;

export function ListPresets():Promise<Array<preset.Preset>>;

export function ListPresetsByType(arg1:string):Promise<Array<preset.Preset>>;

export function ListPrompts():Promise<Array<preset.SavedPrompt>>;

export function ListResolutions():Promise<Array<preset.Resolution>>;

export function ListSavedScenes():Promise<Array<preset.SavedScene>>;

export function ListSessions():Promise<Array<preset.SessionInfo>>;

export function OpenImportCompoundFile():Promise<importexport.CompoundImportPreview>;

export function OpenImportFile():Promise<importexport.ImportPreview>;

export function ReadClipboardImage():Promise<string>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function ReadImageFile():Promise<string>;

export function ReadThumbnail(arg1:string):Promise<string>;

export function RecommendPreset(arg1:string):Promise<generation.RecommendPresetResult>;

export function RenameSession(arg1:number,arg2:string):Promise<void>;

export function SaveExportPreset(arg1:preset.ExportPreset):Promise<preset.ExportPreset>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveScene(arg1:preset.SavedScene):Promise<preset.SavedScene>;

export function SelectBrowserFolder():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetActiveSessionItem(arg1:number):Promise<void>;

export function SetKidsCategory(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function SetKidsMode(arg1:boolean,arg2:string):Promise<void>;

export function SetLastImage(arg1:string):Promise<void>;

export function SwitchSession(arg1:number):Promise<void>;

export function TestCompoundGenerate(arg1:generation.TestCompoundGenerateParams):Promise<Array<generation.TestGenerateResultItem>>;

export function TestGenerate(arg1:generation.TestGenerateParams):Promise<Array<generation.TestGenerateResultItem>>;

export function UpdateCompoundPreset(arg1:preset.CompoundPreset):Promise<preset.CompoundPreset>;

export function UpdateDescription(arg1:preset.SavedDescription):Promise<void>;

export function UpdateHiresProfile(arg1:preset.HiresProfile):Promise<preset.HiresProfile>;

export function UpdatePreset(arg1:preset.Preset):Promise<preset.Preset>;

export function UpdatePresetType(arg1:preset.PresetType):Promise<preset.PresetType>;

export function UpdateResolution(arg1:preset.Resolution):Promise<preset.Resolution>;

export function UpdateSavedScene(arg1:preset.SavedScene):Promise<preset.SavedScene>;

export function UpdateSettings(arg1:Record<string, string>):Promise<void>;

export function UpscaleImage(arg1:generation.UpscaleImageParams):Promise<generation.GenerateImageResult>;

export function UpscalePreview(arg1:generation.UpscalePreviewParams):Promise<generation.GenerateImageResult>;

export function ValidateImportModels(arg1:Array<importexport.PresetData>):Promise<Array<importexport.ValidationWarning>>;

export function Version():Promise<string>;
