import {
  ListPresets, ListPresetsByType, CreatePreset, UpdatePreset, DeletePreset,
  GenerateSDPrompt, GenerateImage, UpscaleImage, UpscalePreview, SaveImage, GetLastImage,
  GetSDModels, GetSDSamplers, GetSDSchedulers, GetSDUpscalers, GetSDVAEs, GetLLMModels,
  GetSettings, UpdateSettings, CheckServices,
  ListDescriptions, CreateDescription, CreateDescriptionFull, UpdateDescription, DeleteDescription,
  ListPrompts, CreatePrompt, DeletePrompt,
  SetKidsMode, IsKidsModeActive, GetKidsCategories, SetKidsCategory,
  ExportPresets, OpenImportFile, ImportPresets,
  AnalyzeImage, ReadImageFile, ReadClipboardImage,
  ListPresetTypes, GetPresetType, CreatePresetType, UpdatePresetType, DeletePresetType,
  GetAllTags, GetSDLoRAs, ValidateImportModels,
  RecommendPreset, GetDefaultPromptInstruction, GetDefaultAnalyzePrompts,
  BatchGenerate, SelectFolder, GetPresetForBatch,
  TestGenerate,
  ListCompoundPresets, GetCompoundPreset, CreateCompoundPreset, UpdateCompoundPreset, DeleteCompoundPreset,
  GenerateCompoundImage, BatchCompoundGenerate, TestCompoundGenerate,
  GenerateFromImage,
  DecomposeScene, GenerateMultiPass,
  ListSavedScenes, GetSavedScene, SaveScene, UpdateSavedScene, DeleteSavedScene,
  CheckRembg,
  ClearLastImage,
  ListExportPresets, SaveExportPreset, DeleteExportPreset, ExportImage,
  BrowseDirectory, ReadFileAsBase64, ReadThumbnail, SelectBrowserFolder, SetLastImage,
  CreateSession, ListSessions, SwitchSession, RenameSession, DeleteSession,
  GetSessionItems, GetActiveSessionItem, SetActiveSessionItem, DeleteSessionItem,
  ClearSession, GetSessionImage, GetSessionThumb, HasSessionItems, ConfirmClose,
  InterruptGeneration,
} from './wailsjs/go/main/App.js'

export const api = {
  listPresets: () => ListPresets(),
  listPresetsByType: (type) => ListPresetsByType(type),
  createPreset: (data) => CreatePreset(data),
  updatePreset: (id, data) => UpdatePreset({ ...data, id }),
  deletePreset: (id) => DeletePreset(id),
  generateSdPrompt: (params) => GenerateSDPrompt(params),
  generateImage: (presetId, extraPrompt, extraNegativePrompt) =>
    GenerateImage({ preset_id: presetId, extra_prompt: extraPrompt, extra_negative_prompt: extraNegativePrompt }),
  upscalePreview: (previewImageBase64, presetId, seed) =>
    UpscalePreview({ preview_image_base64: previewImageBase64, preset_id: presetId, seed }),
  upscaleImage: (imageBase64, genInfo, presetId) =>
    UpscaleImage({ image_base64: imageBase64, gen_info: typeof genInfo === 'string' ? genInfo : JSON.stringify(genInfo || {}), preset_id: presetId || 0 }),
  saveImage: (base64Data, defaultName) => SaveImage(base64Data, defaultName),
  getLastImage: () => GetLastImage(),
  getModels: () => GetSDModels(),
  getSamplers: () => GetSDSamplers(),
  getSchedulers: () => GetSDSchedulers(),
  getUpscalers: () => GetSDUpscalers(),
  getVAEs: () => GetSDVAEs(),
  getLLMModels: () => GetLLMModels(),
  getSettings: () => GetSettings(),
  updateSettings: (data) => UpdateSettings(data),
  checkServices: () => CheckServices(),
  listDescriptions: () => ListDescriptions(),
  createDescription: (text) => CreateDescription(text),
  createDescriptionFull: (data) => CreateDescriptionFull(data),
  updateDescription: (data) => UpdateDescription(data),
  deleteDescription: (id) => DeleteDescription(id),
  listPrompts: () => ListPrompts(),
  createPrompt: (text) => CreatePrompt(text),
  deletePrompt: (id) => DeletePrompt(id),
  setKidsMode: (enabled, pin) => SetKidsMode(enabled, pin),
  isKidsModeActive: () => IsKidsModeActive(),
  getKidsCategories: () => GetKidsCategories(),
  setKidsCategory: (name, enabled, pin) => SetKidsCategory(name, enabled, pin),
  exportPresets: (ids) => ExportPresets(ids),
  openImportFile: () => OpenImportFile(),
  importPresets: (items) => ImportPresets(items),
  analyzeImage: (imageBase64) => AnalyzeImage(imageBase64),
  readImageFile: () => ReadImageFile(),
  readClipboardImage: () => ReadClipboardImage(),
  listPresetTypes: () => ListPresetTypes(),
  getPresetType: (id) => GetPresetType(id),
  createPresetType: (data) => CreatePresetType(data),
  updatePresetType: (data) => UpdatePresetType(data),
  deletePresetType: (id) => DeletePresetType(id),
  getAllTags: () => GetAllTags(),
  getLoRAs: () => GetSDLoRAs(),
  validateImportModels: (items) => ValidateImportModels(items),
  recommendPreset: (description) => RecommendPreset(description),
  getDefaultPromptInstruction: () => GetDefaultPromptInstruction(),
  getDefaultAnalyzePrompts: () => GetDefaultAnalyzePrompts(),
  batchGenerate: (params) => BatchGenerate(params),
  selectFolder: () => SelectFolder(),
  getPresetForBatch: (presetId, description) => GetPresetForBatch(presetId, description),
  testGenerate: (params) => TestGenerate(params),
  listCompoundPresets: () => ListCompoundPresets(),
  getCompoundPreset: (id) => GetCompoundPreset(id),
  createCompoundPreset: (data) => CreateCompoundPreset(data),
  updateCompoundPreset: (data) => UpdateCompoundPreset(data),
  deleteCompoundPreset: (id) => DeleteCompoundPreset(id),
  generateCompoundImage: (params) => GenerateCompoundImage(params),
  batchCompoundGenerate: (params) => BatchCompoundGenerate(params),
  testCompoundGenerate: (params) => TestCompoundGenerate(params),
  generateFromImage: (params) => GenerateFromImage(params),
  decomposeScene: (params) => DecomposeScene(params),
  generateMultiPass: (scene) => GenerateMultiPass(scene),
  listSavedScenes: () => ListSavedScenes(),
  getSavedScene: (id) => GetSavedScene(id),
  saveScene: (data) => SaveScene(data),
  updateSavedScene: (data) => UpdateSavedScene(data),
  deleteSavedScene: (id) => DeleteSavedScene(id),
  checkRembg: () => CheckRembg(),
  clearLastImage: () => ClearLastImage(),
  listExportPresets: () => ListExportPresets(),
  saveExportPreset: (data) => SaveExportPreset(data),
  deleteExportPreset: (id) => DeleteExportPreset(id),
  exportImage: (params) => ExportImage(params),
  browseDirectory: (path) => BrowseDirectory(path),
  readFileAsBase64: (path) => ReadFileAsBase64(path),
  readThumbnail: (path) => ReadThumbnail(path),
  selectBrowserFolder: () => SelectBrowserFolder(),
  setLastImage: (base64) => SetLastImage(base64),

  createSession: (name) => CreateSession(name),
  listSessions: () => ListSessions(),
  switchSession: (id) => SwitchSession(id),
  renameSession: (id, name) => RenameSession(id, name),
  deleteSession: (id) => DeleteSession(id),
  getSessionItems: () => GetSessionItems(),
  getActiveSessionItem: () => GetActiveSessionItem(),
  setActiveSessionItem: (id) => SetActiveSessionItem(id),
  deleteSessionItem: (id) => DeleteSessionItem(id),
  clearSession: () => ClearSession(),
  getSessionImage: (id) => GetSessionImage(id),
  getSessionThumb: (id) => GetSessionThumb(id),
  hasSessionItems: () => HasSessionItems(),
  confirmClose: (action) => ConfirmClose(action),
  interruptGeneration: () => InterruptGeneration(),
}
