import {
  ListPresets, ListPresetsByType, CreatePreset, UpdatePreset, DeletePreset,
  GenerateSDPrompt, GenerateImage, SaveImage,
  GetSDModels, GetSDSamplers, GetSDSchedulers, GetSDUpscalers, GetSDVAEs, GetLLMModels,
  GetSettings, UpdateSettings, CheckServices,
  ListDescriptions, CreateDescription, DeleteDescription,
  ListPrompts, CreatePrompt, DeletePrompt,
  SetKidsMode, IsKidsModeActive,
  ExportPresets, OpenImportFile, ImportPresets,
} from './wailsjs/go/main/App.js'

export const api = {
  listPresets: () => ListPresets(),
  listPresetsByType: (type) => ListPresetsByType(type),
  createPreset: (data) => CreatePreset(data),
  updatePreset: (id, data) => UpdatePreset({ ...data, id }),
  deletePreset: (id) => DeletePreset(id),
  generateSdPrompt: (description, presetType) => GenerateSDPrompt(description, presetType),
  generateImage: (presetId, extraPrompt, extraNegativePrompt) =>
    GenerateImage({ preset_id: presetId, extra_prompt: extraPrompt, extra_negative_prompt: extraNegativePrompt }),
  saveImage: (base64Data, defaultName) => SaveImage(base64Data, defaultName),
  getModels: () => GetSDModels(),
  getSamplers: () => GetSDSamplers(),
  getSchedulers: () => GetSDSchedulers(),
  getUpscalers: () => GetSDUpscalers(),
  getVAEs: () => GetSDVAEs(),
  getLLMModels: () => GetLLMModels(),
  getSettings: () => GetSettings(),
  updateSettings: (data) => UpdateSettings(data),
  checkServices: () => CheckServices(),
  listDescriptions: () => ListDescriptions(),
  createDescription: (text) => CreateDescription(text),
  deleteDescription: (id) => DeleteDescription(id),
  listPrompts: () => ListPrompts(),
  createPrompt: (text) => CreatePrompt(text),
  deletePrompt: (id) => DeletePrompt(id),
  setKidsMode: (enabled, pin) => SetKidsMode(enabled, pin),
  isKidsModeActive: () => IsKidsModeActive(),
  exportPresets: (ids) => ExportPresets(ids),
  openImportFile: () => OpenImportFile(),
  importPresets: (items) => ImportPresets(items),
}
