package config

var AllowedSettings = map[string]bool{
	"llm_url": true, "sd_url": true, "llm_model": true, "sd_prompt_model": true,
	"vision_model": true,
	"llm_backend": true, "llm_keep_alive": true, "llm_num_ctx": true, "llm_num_gpu": true, "llm_max_tokens": true,
	"llm_generate_model": true, "llm_analyze_model": true,
	"llm_generate_temperature": true, "llm_generate_num_ctx": true, "llm_generate_num_predict": true,
	"llm_generate_top_p": true, "llm_generate_num_thread": true,
	"llm_analyze_temperature": true, "llm_analyze_num_ctx": true, "llm_analyze_num_predict": true,
	"llm_analyze_top_p": true, "llm_analyze_num_thread": true,
	"kids_mode": true, "kids_pin_hash": true, "kids_pin_salt": true,
	"kids_cat_violence": true, "kids_cat_horror": true, "kids_cat_weapons": true,
	"kids_cat_substances": true, "kids_cat_mature": true,
	"rembg_url": true,
	"preview_mode": true, "preview_width": true, "preview_height": true,
	"gen_preset_id": true, "gen_action_pose": true, "gen_characters": true,
	"gen_clothing_details": true,
	"gen_environment": true, "gen_lighting": true, "gen_negative": true,
	"gen_extra_prompt": true, "gen_extra_negative": true,
	"gen_description": true, "gen_type_id": true,
	"gen_mode": true, "gen_compound_preset_id": true,
	"gen_resolution_id": true, "gen_hires_profile_id": true,
	"batch_preset_id": true, "batch_compound_preset_id": true, "batch_mode": true,
	"batch_prompt": true, "batch_negative": true, "batch_count": true, "batch_output_folder": true,
	"batch_resolution_id": true, "batch_hires_profile_id": true,
	"test_mode": true, "test_prompt": true, "test_negative": true,
	"test_sampler": true, "test_schedule_type": true, "test_steps": true,
	"test_cfg_scale": true, "test_width": true, "test_height": true,
	"test_resolution_id": true, "test_hires_profile_id": true,
	"fi_mode": true, "fi_preset_id": true, "fi_compound_preset_id": true,
	"fi_gen_mode": true, "fi_denoising": true, "fi_extra_negative": true, "fi_analyze_mode": true,
	"fi_mask_padding": true, "fi_mask_feather": true,
	"theme": true, "file_browser_path": true,
}
